CodeSystem2022/Team-Fortran-Cuarto-Semestre-2023

- Python/Semana 2/Sistemas_Numeracion.py
Se agrega:       
- Decimal, Binario, Octal y Hexadecimal, ahora con int #9 
- Decimal, Binario, Octal y Hexadecimal #8
> Decimal, Binario, Octal y Hexadecimal, ahora con int #9

- Node/Semana01-02-03-04-Node/app.js
- Node/Semana01-02-03-04-Node/app2.js
Se agrego parte del proyecto de la segunda semana.
> Proyecto Node

- Node/Semana01-02-03-04-Node/app3.js
-3.2 Utilizamos el setTimeOut y hacemos pruebas en ejecución#45 
-4.2 EventLoop -> bucle de elementos Parte 1 y 2#46
> Se agrega clase 3 y 4 a node.

- .gitignore
- Python/Semana 3/tipo_bool.py
- Python/Semana 3/tipo_nan.py
- Python/Semana 3/tipo_str.py
Se agrega:
- Semana 3 - Python - completa
- Archivo .gitignore del repositorio
> Semana 3 Python y Archivo .gitignore

- Python/Semana 5/doc_str.py
Se agrego la parte 2 de Dunder doc.
> 5.2 Dunder doc (__doc__) -> parte 2 #70

- Python/Semana 5/metodo_join.py
Método join para colecciones a cadenas
> Método join para colecciones a cadenas -> Parte 1

- JavaScript/E_Commerce/Client/Js/cart.js
- Node/Semana 5/monohilo.js
> Parte 1 -> Instalación = npm init ...creamos un json #109

- JavaScript/E_Commerce/Server/server.js
Creamos el archivo server.js pegar código de Github
> Creamos el archivo server.js pegar código de Github

- JavaScript/E_Commerce/Client/Js/cart.js
- JavaScript/E_Commerce/index.html
SDK Mercado pago en index.html
Botón mercado pago en cart.js
> Parte 5 - Botón de mercado pago

- Java/Semana 2/estudiantes/src/main/java/utn/estudiantes/EstudiantesApplication.java
- Java/Semana 2/estudiantes/src/main/resources/application.properties
- Java/Semana 2/estudiantes/src/main/resources/logback-spring.xml
- Python/Semana 5/metodo_split.py
Ejecución y limpieza de consola#124
> Ejecución y limpieza de consola#124-Morales Gaston

- Node/Semana 6/entorno.js
Se agrega:
- 6.1 Configurar variables de entorno #262 
- 6.2 Pruebas para aclarar conceptos #263 
- 6.3 Buenas prácticas en Node #264
> Clase 06: Variables de Entorno

- Java/Semana 2-3-4-5/estudiantes/src/main/java/utn/estudiantes/EstudiantesApplication.java
>  Listar Estudiantes

- Java/Semana 6-7-8/tienda_libros/src/main/resources/logback-spring (1).xml
Abrimos el proyecto y configuramos Parte 1 y Parte 2 ->
> Abrir proyecto#287 Morales Gaston

- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/controllers/tareas.controllers.js
- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/router/tareas.routers.js
*Cambios asignados de los issues semana 6 JS
> Facundo pereyra

- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/controllers/tareas.controllers.js
- 6.4 Método para obtener tarea -> listarTarea => ahora en singular #278 + formateo de codigo
- 6.5 Método eliminarTarea #279
- 6.6 Método actualizarTarea #278
> Clase 06 JS - Proyecto Daniel Guerrero

- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/index.js
> Se actualiza archivo index.js

- Java/Semana 6-7-8/tienda_libros/src/main/resources/application.properties
> 6.3 Abrimos el proyecto y configuramos Parte 3 -> Conexión a la base  #289

- Node/Semana 7/entorno.js
- Node/Semana 7/monohilo.js
7.1 Nodemon -> herramienta para el desarrollo
7.2 Problemas con Window -> ejecución de nodemon
7.3 PM2 -> herramienta para producción
7.4 Ejecución de PM2
> Clase 07 - Node

- Java/Semana 6-7-8/tienda_libros/src/main/java/utn/tienda_libros/modelo/Libro.java
- Java/Semana 6-7-8/tienda_libros/src/main/java/utn/tienda_libros/repositorio/LibroRepositorio.java
Creación de la tabla libro en la base de datos
Capa de Datos -> JpaRepository
> 7.1 Clase entidad Libro#305 Morales Gaston

- JavaScript/Proyecto con stack pern (Daniel Guerrero)/database/init.sql
- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/controllers/auth.controllers.js
- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/router/auth.router.js
7.1 Registro -> Archivo auth.routes.js => signup #311
7.2 Utilización de bcrypt para proteger el password #312
> 7.1 Registro - 7.2 Utilización de bcrypt

- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/controllers/auth.controllers.js
- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/libs/jwt.js
Se agrega: 
- 7.3 Creación del token -> conectando con el frontend #313 
- 7.4 Cookies -> Guardar el token en una cookie #314
> 7.3 Creación del token -> conectando con el frontend - 7.4 Cookies -> Guardar el token en una cookie

- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/app.js
- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/controllers/tareas.controllers.js
- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/middlewares/auth.middleware.js
- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/router/auth.router.js
- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/router/tareas.routers.js
7.5 Creación de un middleware -> auth.middleware.js#315
> 7.5 Creación de un middleware -> auth.middleware.js

- Java/Semana 6-7-8/tienda_libros/src/main/java/utn/tienda_libros/servicio/ILibroServicio.java
- Java/Semana 6-7-8/tienda_libros/src/main/java/utn/tienda_libros/servicio/LibroServicio.java
- Java/Semana 6-7-8/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.form
- Java/Semana 6-7-8/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.java
Tareas realizadas:
7.4 Capa de Servicio -> Esto es de buenas prácticas
Parte 1 -> Interface ILibroServicio
Parte 2 -> Clase LibroServicio => implementación
7.5 Capa de Presentación -> Swing
7.6 Constructor para la inyección de dependencias de Spring
> Parte final clase 7 Java

- JavaScript/Proyecto con stack pern (Daniel Guerrero)/src/controllers/auth.controllers.js
> 8.1 Inicio de sesión -> signin #339

- JavaScript/Proyecto con stack pern (Daniel Guerrero)/frontend/src/components/ui/Button.jsx
- JavaScript/Proyecto con stack pern (Daniel Guerrero)/frontend/src/components/ui/Card.jsx
- JavaScript/Proyecto con stack pern (Daniel Guerrero)/frontend/src/components/ui/input.jsx
- JavaScript/Proyecto con stack pern (Daniel Guerrero)/frontend/src/pages/RegisterPage.jsx
Se agrega: 8.5 Formulario de de registro Parte 1 #343
> Formulario de registro Parte 1 #343

- Node/Semana 8/02-fundamentos_node/async/callback.js
> Morales Gaston#335

- Node/Semana 10/02-Fundamentos_node/async/promises.js
- Node/Semana 11/02-Fundamentos_node/async/asyncAwait.js
- Node/Semana 12/02-Fundamentos_node/modulos/globales.js
- Node/Semana 13/02-Fundamentos-node/modulos/archivo.txt
- Node/Semana 13/02-Fundamentos-node/modulos/fs.js
- Node/Semana 9/02-Fundamentos_node/async/callbackHell.js
Se completan las clases de Node
> Completando clases Node
